version: '3'
services:
  www:
    user: "root:root"
    build: .
    env_file:
      - .environment/conf.env
      - .environment/dev.env
      # - .environment/prod.env
    #volumes:
      #- .\data:/var/lib/postgresql/11/main
    ports:
      - "5432:5432"
    command:
      sh /start.sh